server:
  error:
    include-message: always
    include-binding-errors: always
  servlet:
    context-path: /api
  port: 8080
spring:
  freemarker:
    template-loader-path: classpath:/templates
    suffix: .ftl